### ISSUE TITLE
Events shift after Daylight Savings

### ISSUE THREAD

**Issue by histefanhere** [Excigma/Userscripts#5]
I know UoA has (finally) an alternative to UoACal, but it's missing some of my classes, the events that it exports aren't very clean and littered with useless information. Also, I don't think it's even linked anywhere from UoA (the "Dowload Your Semester Timetable" link in SSO is still a dead link) so for the moment, your script is still the best calendar export method :neutral_face:

There seems to be an issue with how it deals with daylight savings however, because all events during and after the week of Sep 29th are scheduled for an hour later than they should be. Confirmed to be an issue on multiple calendar clients (nextcloud, thunderbird, gnome calendar).

It seems like the timezone is not being specified in the ics file, and because of that recurring events that cross the daylight savings time change are broken. I think the solution involves specifying the NZ timezone in the calendar file, and this could be useful for that: [How to compensate for daylight savings time in the future for ICS file calendar downloads (stackoverflow)](https://stackoverflow.com/questions/72806462/how-to-compensate-for-daylight-savings-time-in-the-future-for-ics-file-calendar) .

**Comment by Excigma** [comment]
Thanks for opening this issue, :smiling_face_with_tear: :sob:. It appears that my friends also get this inconsistently and I've been kinda worried that this would happen (I honestly hate dealing with timezones). I believe I've attempted (evidently unsuccessfully) to use UTC time to avoid this exact issue.

I wanted to avoid using that VTIMEZONE thing that was suggested, as I didn't want to need to hard code things that may change with time, but that might be unavoidable.

> the events that it exports aren't very clean and littered with useless information.

I've been thinking about making a Cloudflare(?) worker that takes an .ics URL and 'cleans' it up. But it can't fix the missing classes....

I'll leave this issue and have a look into this when I can, not sure if I'll get to fixing it for a couple weeks - hope you're okay with this - at the moment I'm just using mytimetable + UoA Kahu app on my phone :/

**Comment by histefanhere** [comment]
> I honestly hate dealing with timezones

Don't we all, I would have thought specifying events in UTC would solve the issue but times are just a horrible thing to work with ig.

> I didn't want to need to hard code things that may change with time

Do you mean the daylight savings definitions? They've been the same for nearly 20 years now, and hopefully if they do change at some point in the distant future UoA will finally have a decent working timetable system of their own. Actually, in saying that that feels more unlikely than daylight savings changing...

Coincidentally I just got invited to a scheduled meeting via Google and took a look at the `invite.ics` it generated, and noticed a lot of things to do with timezones. The start of the file consists of this timezone definition:

```
BEGIN:VCALENDAR
METHOD:REQUEST
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
BEGIN:VTIMEZONE
TZID:New Zealand Standard Time
BEGIN:STANDARD
DTSTART:16010101T030000
TZOFFSETFROM:+1300
TZOFFSETTO:+1200
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=1SU;BYMONTH=4
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETFROM:+1200
TZOFFSETTO:+1300
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=9
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
```

and a `TZID=New Zealand Standard Time` specified in each event. I adapted one of my classes in the second-half of the semester that crosses the start of DYS by adding `TZID` and specifying the datetime in NZ time instead of UTC for `DTSTART` and `DTEND`:

```
BEGIN:VEVENT
UID:3dcbe8f902d1fb0e88d55b8ac677b085f117c666
SUMMARY:COMPSCI 399
DESCRIPTION:COMPSCI 399 Capstone: Computer Science
DTSTAMP:20240719T014316Z
DTSTART;TZID=New Zealand Standard Time:20240909T140000
DTEND;TZID=New Zealand Standard Time:20240909T170000
LOCATION:401-439
RRULE:FREQ=WEEKLY;UNTIL=20241014T110000Z
END:VEVENT
```

Notice it should go from 2PM to 5PM. Lo and behold, shown below is the event in my calendar. The green to the right is the original generated from the script, and the blue to the left is my modified event:

![image](https://github.com/user-attachments/assets/98a49810-f88c-4021-9f23-8081f77f66bc)

> Not sure if I'll get to fixing it for a couple weeks

Not a worry at all, it only affects the last few weeks of semester anyway. I looked into this myself now only because I'm bored :smiley: If you're okay with specifying the TZ like this I can make a PR myself.

**Comment by Excigma** [comment]
> Do you mean the daylight savings definitions? They've been the same for nearly 20 years now, and hopefully if they do change at some point in the distant future UoA will finally have a decent working timetable system of their own. 

Ah, that's good to hear

>  I looked into this myself now only because I'm bored 😃 If you're okay with specifying the TZ like this I can make a PR myself.

Feel free to send through a PR if you're free. No pressure to do it if you get busy though, thank you very much for the investigation into this
